### PR TITLE
Compile/build, xHarbour compatibility

### PR DESCRIPTION
**Pull request by JoseQuintas**
because code is more clean using conversion function.
workflow to compile samples prepared.
I can setup current repository, but I do not know how to change related repository (oohg core).

oohg/core, oohg/doc, oohg/samples, harbour/core, these names are ok on it's original location
But when fork: JoseQuintas/core can't be oohg and harbour at same time.
And JoseQuintas/doc JoseQuintas/samples, may conflict with another repositories too.
I change on fork to: harbour_32, Harbour_34, oohg, oohg_doc, oohg_samples, oohg_ide, oohg_distros
Do not know how adjust this on workflow to works on different names/repositories.

### CODE REVIEW

**Comment by fyurisich** [comment]
Since its beginning OOHG is an xHarbour library.
These changes can't be accepted because they transform OOHG into a native Harbour library and force the use of compatibility functions on xHarbour instead of using native functions.

**Comment by JoseQuintas** [comment]
ok

**Comment by fyurisich** [comment]
José:
Can you please explain me how can I use the workflow?
Thank you.

**Comment by JoseQuintas** [comment]
create a folder .github/workflows
You can use as batch, like a bat file, or like powershell, with more features.
files are visible from net, you can check some of my files as start point.
https://github.com/JoseQuintas/hwgui/tree/main/.github/workflows
I need recover my harbour_32 and harbour_34 repositories with harbour creation, but it exists on hwgui linux workflow
I use a c:\temp folder, because c: have more space than default folder, and c:\temp is not a protected folder.
In a quick way: you can use the same commands in same way you use on computer, all in a batch mode, it is a virtual working machine but you cannot type commands on it, the workflow will run like an enhanced batch file
virtual machine available is a windows server or linux, with default msys2 + mingw + msvc + common tools to development
7zip and others, but you can download from net and make others things inside the machine - allways on workflow like a batch
for C compiler, Harbour and XHarbour, I create a loop workflow, to revalidate expire date, and download from own previous workflow.
I will recover my deleted repositories, because I see now that I deleted the source to create C compilers.
I will create a default one to oohg, and you adjust the paths for official ones.

workflow can run: automatically by date, automatically after each commit, or manually clicking on build on github repository page.
Because oohg is one part on each repository, need some things I do not know, as example start workflow of one repository when another is changed.
But you can create a workflow to run at night on each day, joining all repositories and creating a nightly build with all updated.
it is all free for public repositories.

**Comment by JoseQuintas** [comment]
workflow can be viewed and is downloaded together with source code.
but workflow can generate files, that exists only on workflow run, and exists attached on workflow run.
I discovered a special way to save tools on repository without include them on repository.
In this way, repository have many C compilers, but they are not downloaded when download repository.
This is important, to do not increase size of repository history and repository download.

Only now I see that I destroy several of my workflows on github.
Wait, I will recreate them on hbpack, they can be used as start point.
workflow is this: a file with extension .yml, saved on .github/workflows folder.
And when download repository, or create a fork, these files will be copied too.
And when you make a commit, the yml files will be saved on github, and will be ready to run.

**Pull request closed without merging**
