### PR TITLE
first source format fully automatic

### PR DESCRIPTION
**Pull request by JoseQuintas**
My first full automatic format.
I will test each file to confirm result, and as a last option, will change manually the source code.

Yes!!! a Format code utility!!!

### CODE REVIEW

**Comment by JoseQuintas** [comment]
Incredible !! It is working !!!!

**Comment by fyurisich** [comment]
Congratulations!
May be later you can help with oohg's formatter.
I'll be merging the pull request asap.

**Comment by JoseQuintas** [comment]
It is on a old style. 
At momment, may be dangerous to user, then do not include on oohg repository.
It is on my "draft" folder.
PRG: https://github.com/JoseQuintas/JoseQuintas/blob/master/drafts/hmgformat.prg
CH: https://github.com/JoseQuintas/JoseQuintas/blob/master/drafts/hmgformat.ch

And a test of a batch file to compile:
https://github.com/JoseQuintas/JoseQuintas/blob/master/drafts/compileaux.bat

It is interesting to "create functions" on bat.

```
FOR %%a IN (a b c d e) do call :show %%a
goto :END

:SHOW
   echo %1
   goto :END

:END
```

result:
```
a
b
c
d
e
``` 

Note: the "function" ends on the end of the batch.
Now check on that bat the "functions" compile, compile_prg, compile_c...

**Comment by fyurisich** [comment]
Too many changes and too little time to check them.

**Pull request closed without merging**
